### ISSUE TITLE
Kiritilgan qiymat manfiy bo'lmagani yaxshi )

### ISSUE THREAD

**Issue by udilbar** [abdulatifkhan/letsgo#2]
![Screenshot_14](https://user-images.githubusercontent.com/68459485/98669569-605f4680-2373-11eb-9ccb-3f95e1546fb0.png)
Inputga manfiy qimmat kiritilganida ham ishlayapti. Inputga masofani faqat musbat son bilan kiritilinadigan qilib qo'yganimiz yaxshiroq )

**Comment by abdulatifkhan** [comment]
Katta rahmat, kamchilikni bartaraf etdik)
